// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package org.github.grpc.examples.helloworld;

public interface SampleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sample.SampleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   *
   * @return The name.
   */
  java.lang.String getName();

  /**
   * <code>string name = 1;</code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
  getNameBytes();
}
