// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package org.github.grpc.examples.helloworld;

public interface SampleReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sample.SampleReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   *
   * @return The message.
   */
  java.lang.String getMessage();

  /**
   * <code>string message = 1;</code>
   *
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
  getMessageBytes();
}
